[package]
name = "nect-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nect = { path = "..", features = ["fuzz"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_lexer"
path = "fuzz_targets/fuzz_lexer.rs"

[[bin]]
name = "fuzz_parser"
path = "fuzz_targets/fuzz_parser.rs"

[[bin]]
name = "fuzz_vm"
path = "fuzz_targets/fuzz_vm.rs"

[[bin]]
name = "fuzz_interpreter"
path = "fuzz_targets/fuzz_interpreter.rs"